### ISSUE TITLE
Implement a 1D integration grid

### ISSUE THREAD

**Issue by tovrstra** [theochem/qcgrids#3]
We have something reasonably good in HORTON. It would however be good to see if we can make a better 1D integration and interpolation, e.g. using https://github.com/scipy/scipy/blob/master/scipy/special/orthogonal.py

**Comment by PaulWAyers** [comment]
I think I have a set of notes on good 1D integration methods, even code in some cases. That is on a specified interval ([a,b]) and not on [0,infinity] or [-infinity,infinity].

**Comment by PaulWAyers** [comment]
I'd also tend to use ORTHPOL which is Walter Gautschi's code (now translated into Python). that's probably the best code around, or was as of the last time I looked.

https://anaconda.org/pypi/orthpol

There is github and several other things.

**Comment by PaulWAyers** [comment]
Here are some things from my old notes.  A lot of it is redundant.  I have somewhere another set of notes with Clenshaw-Curtis formulae.


[QuadratureFormulae1D.pdf](https://github.com/theochem/qcgrids/files/1251917/QuadratureFormulae1D.pdf)
[1Dgrids.pdf](https://github.com/theochem/qcgrids/files/1251920/1Dgrids.pdf)
[grids2.pdf](https://github.com/theochem/qcgrids/files/1251922/grids2.pdf)

**Comment by tovrstra** [comment]
This will be done in the python grids package.
