### ISSUE TITLE
Linking fails

### ISSUE THREAD

**Issue by matt-chan** [theochem/qcgrids#31]
We can't link successfully unless all the dependencies are using the same compiler/libstdc++. This is particularly a problem because old versions of cellcutoffs were built with gcc4.8/libstdc++(gcc) and new versions of conda python and osx qcgrids is now built with clang/libc++(llvm). The symbols aren't the same between the two anymore, so builds are failing.

**Comment by tovrstra** [comment]
@matt-chan I guess we should fix the clang builds first and then remove older binary packages for osx that cause these inconsistencies.
